/* Derives web-sized images from the originals.
 *
 *   node scripts/build-images.js          # write assets/images/v5w/**
 *   node scripts/build-images.js --check  # fail if a derived file is missing/stale
 *
 * WHY THIS EXISTS
 * ---------------
 * The source art is full-resolution: 60 PNGs, 101MB, portraits at 1254x1254 that
 * the page renders at 88px. Shipping that is a Core Web Vitals failure on its own.
 *
 * THE ORIGINALS ARE NEVER TOUCHED. They are the only copies that exist and they
 * cannot be regenerated, so this only ever writes into a separate `v5w/` tree.
 * Delete that tree and re-run and you are back where you started.
 */
const fs = require('fs');
const path = require('path');
const sharp = require('d:/Flowsmartly/flowsmartly/node_modules/sharp');

const SRC = path.join(__dirname, '..', 'assets', 'images', 'v5');
/** Backdrop-free versions written by scripts/cutouts.py, preferred when present. */
const CUT = path.join(__dirname, '..', 'assets', 'images', 'v5cut');
const OUT = path.join(__dirname, '..', 'assets', 'images', 'v5w');
/** Which names ended up as cutouts, so the UI can lay them out as artwork. */
const MANIFEST = path.join(__dirname, '..', 'src', 'components', 'public', 'media-cutouts.ts');
const CHECK = process.argv.includes('--check');

/**
 * Widths are set from the largest size each family is actually rendered at,
 * doubled for high-density screens. Portraits top out at ~200px in the
 * leadership cards; scenes fill a half-width column on a 1536px page.
 */
const RULES = [
  { match: /^people\//, width: 512 },
  { match: /^logos\//, width: 512 },
  { match: /^editorial\//, width: 1600 },
  { match: /^scenes\//, width: 1400 },
  { match: /^video\//, width: 1400 },
  { match: /.*/, width: 1200 },
];

/** The brand mark has to stay lossless — a gradient logo shows webp banding. */
const KEEP_PNG = /^(flowsmartly-logo|flowsmartly-mark)$/;

function walk(dir, prefix = '') {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full, `${prefix}${entry.name}/`));
    else if (/\.(png|jpe?g)$/i.test(entry.name)) out.push({ full, rel: `${prefix}${entry.name}` });
  }
  return out;
}

function widthFor(rel) {
  return RULES.find((rule) => rule.match.test(rel)).width;
}

/**
 * A cutout has to be laid out differently from a photograph — contained inside
 * a plate with room around it, never cropped to fill a box — so the UI needs to
 * know which is which. Generating the list means it can never drift from what
 * the pipeline actually produced.
 */
function writeManifest(names, artboards) {
  const artboardBody = artboards
    .sort()
    .map((name) => `  '${name}',`)
    .join('\n');
  const body = names
    .sort()
    .map((name) => `  '${name}',`)
    .join('\n');
  const file = `/* GENERATED by scripts/build-images.js — do not edit by hand. */

/**
 * Assets whose flat backdrop has been removed, so they carry real transparency.
 *
 * These are artwork, not photographs: they must be laid out with
 * \`contentFit="contain"\` and breathing room, never cropped to fill a box. The
 * originals were 3D renders on a flat lavender plate, which read as pasted-in
 * rectangles — glaring light blocks in the grey and dark themes.
 */
export const CUTOUTS: ReadonlySet<string> = new Set([
${body}
]);

/**
 * Registry keys and derived-file names do not always agree: the editorial art
 * lives in a subfolder so both sides read editorial/blog-cart-recovery, but
 * the product shots are flat files (product-commuter-backpack.png) that the
 * media registry addresses as product/commuter-backpack. Comparing raw, all
 * four product cutouts reported false — so they were laid out as photographs
 * and cropped to fill, which is exactly what a cutout must never do.
 */
function key(name: string): string {
  return name.split('/').join('-');
}

export function isCutout(name: string): boolean {
  return CUTOUTS.has(key(name));
}

/**
 * Illustrations that were deliberately NOT cut out, because their art is
 * painted into the backdrop — a motion trail, a pane of glass, a wisp of smoke.
 * Lifted off the lavender they became grey smears, so they keep it and get an
 * artboard instead: a light plate in every theme, which reads as a deliberate
 * frame rather than as a backdrop that leaked.
 */
export const ARTBOARDS: ReadonlySet<string> = new Set([
${artboardBody}
]);

export function isArtboard(name: string): boolean {
  return ARTBOARDS.has(key(name));
}
`;
  fs.mkdirSync(path.dirname(MANIFEST), { recursive: true });
  fs.writeFileSync(MANIFEST, file);
}

(async () => {
  if (!fs.existsSync(SRC)) {
    console.error(`no source images at ${SRC}`);
    process.exit(1);
  }
  const files = walk(SRC);
  let written = 0;
  let skipped = 0;
  const stale = [];
  let srcBytes = 0;
  let outBytes = 0;

  const cutouts = [];

  for (const file of files) {
    const base = file.rel.replace(/\.(png|jpe?g)$/i, '');
    const lossless = KEEP_PNG.test(base);
    const target = path.join(OUT, `${base}.${lossless ? 'png' : 'webp'}`);

    // A cutout supersedes the original: same name, no backdrop, already
    // cropped to the subject. WebP carries the alpha, so nothing is lost.
    const cutSource = path.join(CUT, `${base}.png`);
    const source = fs.existsSync(cutSource) ? cutSource : file.full;
    if (source === cutSource) cutouts.push(base);

    const srcStat = fs.statSync(source);
    srcBytes += srcStat.size;

    const fresh =
      fs.existsSync(target) && fs.statSync(target).mtimeMs >= srcStat.mtimeMs;
    if (fresh) {
      skipped += 1;
      outBytes += fs.statSync(target).size;
      continue;
    }
    if (CHECK) {
      stale.push(file.rel);
      continue;
    }

    fs.mkdirSync(path.dirname(target), { recursive: true });
    const pipeline = sharp(source).resize({
      width: widthFor(file.rel),
      // never upscale a source that is already smaller than the target
      withoutEnlargement: true,
    });
    await (lossless
      ? pipeline.png({ compressionLevel: 9, palette: true }).toFile(target)
      : pipeline.webp({ quality: 82, effort: 5 }).toFile(target));
    written += 1;
    outBytes += fs.statSync(target).size;
  }

  if (CHECK) {
    if (stale.length) {
      console.error(`${stale.length} derived image(s) missing or stale:\n  ${stale.join('\n  ')}`);
      console.error('\nrun: node scripts/build-images.js');
      process.exit(1);
    }
    console.log(`all ${files.length} derived images are current`);
    return;
  }

  const artboardFile = path.join(OUT, '.artboards.json');
  const artboards = fs.existsSync(artboardFile)
    ? JSON.parse(fs.readFileSync(artboardFile, 'utf8'))
    : [];
  writeManifest(cutouts, artboards);

  const mb = (n) => `${(n / 1048576).toFixed(1)}MB`;
  console.log(`${files.length} source image(s): ${written} written, ${skipped} already current`);
  console.log(`${mb(srcBytes)} -> ${mb(outBytes)}  (${Math.round((1 - outBytes / srcBytes) * 100)}% smaller)`);
  console.log(`${cutouts.length} of them are backdrop-free cutouts`);
})();
