/* GENERATED by scripts/build-images.js — do not edit by hand. */

/**
 * Assets whose flat backdrop has been removed, so they carry real transparency.
 *
 * These are artwork, not photographs: they must be laid out with
 * `contentFit="contain"` and breathing room, never cropped to fill a box. The
 * originals were 3D renders on a flat lavender plate, which read as pasted-in
 * rectangles — glaring light blocks in the grey and dark themes.
 */
export const CUTOUTS: ReadonlySet<string> = new Set([

]);

/**
 * Registry keys and derived-file names do not always agree: the editorial art
 * lives in a subfolder so both sides read editorial/blog-cart-recovery, but
 * the product shots are flat files (product-commuter-backpack.png) that the
 * media registry addresses as product/commuter-backpack. Comparing raw, all
 * four product cutouts reported false — so they were laid out as photographs
 * and cropped to fill, which is exactly what a cutout must never do.
 */
function key(name: string): string {
  return name.split('/').join('-');
}

export function isCutout(name: string): boolean {
  return CUTOUTS.has(key(name));
}

/**
 * Illustrations that were deliberately NOT cut out, because their art is
 * painted into the backdrop — a motion trail, a pane of glass, a wisp of smoke.
 * Lifted off the lavender they became grey smears, so they keep it and get an
 * artboard instead: a light plate in every theme, which reads as a deliberate
 * frame rather than as a backdrop that leaked.
 */
export const ARTBOARDS: ReadonlySet<string> = new Set([
  'editorial/blog-ai-conversations',
  'editorial/blog-analytics',
  'editorial/blog-cart-recovery',
  'editorial/blog-local-growth',
  'editorial/blog-omnichannel',
  'editorial/blog-social-dms',
  'editorial/customer-story-1',
  'editorial/customer-story-2',
  'editorial/customer-story-3',
  'editorial/guide-playbook-cover',
  'editorial/guide-playbook-spread',
  'editorial/press-kit',
  'editorial/resource-automation',
  'editorial/resource-deliverability',
  'editorial/resource-getting-started',
  'editorial/resource-storefront',
  'editorial/security-shield',
  'editorial/template-library',
]);

export function isArtboard(name: string): boolean {
  return ARTBOARDS.has(key(name));
}
