/**
 * Nginx Config Generator — generates reverse proxy configs for independent SSR apps.
 *
 * Generates a single file at /etc/nginx/conf.d/flowsmartly-apps.conf with
 * upstream + location blocks for all running SSR stores and websites.
 *
 * On dev (Windows), this is a no-op — apps are accessed directly by port.
 */

import { execSync } from "child_process";
import { writeFileSync, existsSync, mkdirSync } from "fs";
import { prisma } from "@/lib/db/client";

const IS_PRODUCTION = process.platform === "linux";
const NGINX_CONF_PATH = "/etc/nginx/conf.d/flowsmartly-apps.conf";

// ─── Generate config for a single store ──────────────────────────────────────

function generateStoreBlock(slug: string, port: number): string {
  const safeName = slug.replace(/[^a-z0-9_-]/gi, "_");
  return `
# Store: ${slug} → port ${port}
upstream store_${safeName} {
    server 127.0.0.1:${port};
}

location /stores/${slug}/ {
    proxy_pass http://store_${safeName}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Store-Slug ${slug};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
}
`;
}

// ─── Generate config for a single website ────────────────────────────────────

function generateWebsiteBlock(slug: string, port: number): string {
  const safeName = slug.replace(/[^a-z0-9_-]/gi, "_");
  return `
# Website: ${slug} → port ${port}
upstream site_${safeName} {
    server 127.0.0.1:${port};
}

location /sites/${slug}/ {
    proxy_pass http://site_${safeName}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Site-Slug ${slug};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
}
`;
}

// ─── Regenerate the entire nginx config and reload ───────────────────────────

export async function regenerateAndReload(): Promise<void> {
  if (!IS_PRODUCTION) {
    console.log("[nginx-config] Skipping on non-Linux (dev mode)");
    return;
  }

  // Fetch all running SSR apps
  const [stores, websites] = await Promise.all([
    prisma.store.findMany({
      where: {
        ssrPort: { not: null },
        ssrStatus: { in: ["running", "starting"] },
        storeVersion: "independent",
      },
      select: { slug: true, ssrPort: true },
    }),
    prisma.website.findMany({
      where: {
        ssrPort: { not: null },
        ssrStatus: { in: ["running", "starting"] },
      },
      select: { slug: true, ssrPort: true },
    }),
  ]);

  // Build config
  let config = `# Auto-generated by FlowSmartly SSR Manager\n# DO NOT EDIT — regenerated on every deploy/start/stop\n# Generated: ${new Date().toISOString()}\n`;

  for (const store of stores) {
    if (store.ssrPort) {
      config += generateStoreBlock(store.slug, store.ssrPort);
    }
  }

  for (const website of websites) {
    if (website.ssrPort) {
      config += generateWebsiteBlock(website.slug, website.ssrPort);
    }
  }

  // Write and reload
  try {
    writeFileSync(NGINX_CONF_PATH, config, "utf-8");
    console.log(`[nginx-config] Wrote ${NGINX_CONF_PATH} (${stores.length} stores, ${websites.length} websites)`);

    // Test config before reload
    execSync("nginx -t", { stdio: "pipe", timeout: 10_000 });

    // Graceful reload (no downtime)
    execSync("nginx -s reload", { stdio: "pipe", timeout: 10_000 });
    console.log("[nginx-config] Nginx reloaded successfully");
  } catch (err: any) {
    console.error("[nginx-config] Failed to reload nginx:", err.message);
    throw new Error(`Nginx config error: ${err.message}`);
  }
}

/**
 * Generate nginx upstream config for a custom domain pointing to an SSR app.
 * This is added to the main nginx server block for the custom domain.
 */
export function generateCustomDomainProxy(port: number): string {
  return `
    proxy_pass http://127.0.0.1:${port};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
`;
}
