/**
 * Nginx Config Generator — generates reverse proxy configs for independent SSR apps.
 *
 * Architecture:
 *  - /etc/nginx/conf.d/flowsmartly-upstreams.conf  — upstream blocks (valid at http level)
 *  - /etc/nginx/flowsmartly-locations/             — per-app location files (included inside server block)
 *  - /etc/nginx/sites-enabled/flowsmartly          — main server block, includes flowsmartly-locations/
 *
 * On dev (Windows), this is a no-op — apps are accessed directly by port.
 */

import { execSync } from "child_process";
import { writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync } from "fs";
import { join } from "path";
import { prisma } from "@/lib/db/client";

const IS_PRODUCTION = process.platform === "linux";
const UPSTREAMS_CONF = "/etc/nginx/conf.d/flowsmartly-upstreams.conf";
const LOCATIONS_DIR = "/etc/nginx/flowsmartly-locations";

// ─── Upstream block (http context) ───────────────────────────────────────────

function upstreamBlock(name: string, port: number): string {
  return `upstream ${name} {\n    server 127.0.0.1:${port};\n}\n`;
}

// ─── Location block (server context) ─────────────────────────────────────────

function storeLocationBlock(slug: string, port: number): string {
  const safeName = `store_${slug.replace(/[^a-z0-9_-]/gi, "_")}`;
  return `# Store: ${slug} -> port ${port}
location /stores/${slug}/ {
    proxy_pass http://${safeName}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Store-Slug ${slug};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
}
`;
}

function websiteLocationBlock(slug: string, port: number): string {
  const safeName = `site_${slug.replace(/[^a-z0-9_-]/gi, "_")}`;
  return `# Website: ${slug} -> port ${port}
location /sites/${slug}/ {
    proxy_pass http://${safeName}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Site-Slug ${slug};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
}
`;
}

// ─── Regenerate the entire nginx config and reload ───────────────────────────

export async function regenerateAndReload(): Promise<void> {
  if (!IS_PRODUCTION) {
    console.log("[nginx-config] Skipping on non-Linux (dev mode)");
    return;
  }

  // Ensure locations directory exists
  if (!existsSync(LOCATIONS_DIR)) {
    mkdirSync(LOCATIONS_DIR, { recursive: true });
  }

  // Fetch all running SSR apps
  const [stores, websites] = await Promise.all([
    prisma.store.findMany({
      where: {
        ssrPort: { not: null },
        ssrStatus: { in: ["running", "starting"] },
        storeVersion: "independent",
      },
      select: { slug: true, ssrPort: true },
    }),
    prisma.website.findMany({
      where: {
        ssrPort: { not: null },
        ssrStatus: { in: ["running", "starting"] },
      },
      select: { slug: true, ssrPort: true },
    }),
  ]);

  const header = `# Auto-generated by FlowSmartly SSR Manager\n# DO NOT EDIT - regenerated on every deploy/start/stop\n# Generated: ${new Date().toISOString()}\n\n`;

  // 1. Write upstream blocks to conf.d (http context - valid here)
  let upstreams = header;
  for (const store of stores) {
    if (store.ssrPort) {
      const safeName = `store_${store.slug.replace(/[^a-z0-9_-]/gi, "_")}`;
      upstreams += upstreamBlock(safeName, store.ssrPort);
    }
  }
  for (const website of websites) {
    if (website.ssrPort) {
      const safeName = `site_${website.slug.replace(/[^a-z0-9_-]/gi, "_")}`;
      upstreams += upstreamBlock(safeName, website.ssrPort);
    }
  }
  writeFileSync(UPSTREAMS_CONF, upstreams, "utf-8");

  // 2. Write per-app location files (included inside the server block)
  // Remove stale location files first
  try {
    for (const f of readdirSync(LOCATIONS_DIR)) {
      unlinkSync(join(LOCATIONS_DIR, f));
    }
  } catch {}

  for (const store of stores) {
    if (store.ssrPort) {
      const content = header + storeLocationBlock(store.slug, store.ssrPort);
      writeFileSync(join(LOCATIONS_DIR, `store-${store.slug}.conf`), content, "utf-8");
    }
  }
  for (const website of websites) {
    if (website.ssrPort) {
      const content = header + websiteLocationBlock(website.slug, website.ssrPort);
      writeFileSync(join(LOCATIONS_DIR, `site-${website.slug}.conf`), content, "utf-8");
    }
  }

  console.log(`[nginx-config] Wrote ${stores.length} store + ${websites.length} website configs`);

  // 3. Test and reload
  try {
    execSync("nginx -t", { stdio: "pipe", timeout: 10_000 });
    execSync("nginx -s reload", { stdio: "pipe", timeout: 10_000 });
    console.log("[nginx-config] Nginx reloaded successfully");
  } catch (err: any) {
    console.error("[nginx-config] Failed to reload nginx:", err.message);
    throw new Error(`Nginx config error: ${err.message}`);
  }
}

/**
 * Generate nginx upstream config for a custom domain pointing to an SSR app.
 * This is added to the main nginx server block for the custom domain.
 */
export function generateCustomDomainProxy(port: number): string {
  return `
    proxy_pass http://127.0.0.1:${port};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60s;
    proxy_buffering off;
`;
}
