/* GENERATED by scripts/build-content.js — do not edit.
 * Source: src/content/changelog/*.md
 */

import type { ChangelogEntry } from './types';

export const CHANGELOG: ChangelogEntry[] = [
  {
    "date": "2026-08-09",
    "month": "August 2026",
    "label": "Aug 9",
    "kind": "New",
    "title": "The blog, and the pipeline behind it",
    "lines": [
      "Posts are written in markdown and compiled to typed content, so every article inherits the site's type scale and all three themes rather than arriving as markup with styling of its own.",
      "Each post exports as its own page, and the RSS feed, the sitemap dates and the summary answer engines read are all generated from the same index."
    ],
    "more": "/resources/blog"
  },
  {
    "date": "2026-08-08",
    "month": "August 2026",
    "label": "Aug 8",
    "kind": "Improved",
    "title": "The company pages say only what is true",
    "lines": [
      "The press page carried five headlines under real trade titles, a $32M funding round and a fact sheet marked cleared for publication. None of it was real, and all of it is gone.",
      "About drops a company history and a traction band that never happened, and both leadership grids are down to the one founder who has been confirmed."
    ],
    "more": "/company/press"
  },
  {
    "date": "2026-08-08",
    "month": "August 2026",
    "label": "Aug 8",
    "kind": "Fixed",
    "title": "The theme you pick is the theme you get back",
    "lines": [
      "Light, grey and dark are all shipping states, but the choice was not surviving a page change — every navigation dropped you back to where you started.",
      "The theme a visitor picks is now the theme they get back, on the next page and on the next visit."
    ]
  },
  {
    "date": "2026-08-07",
    "month": "August 2026",
    "label": "Aug 7",
    "kind": "New",
    "title": "Written to be found by answer engines",
    "lines": [
      "Every page carries its own title, description, canonical and structured data, and the sitemap and llms.txt are generated from the export itself so they cannot drift from what shipped.",
      "robots.txt now names the AI crawlers that cite their sources and admits them, and blocks the bulk scrapers that neither cite nor refer a visitor."
    ]
  },
  {
    "date": "2026-08-07",
    "month": "August 2026",
    "label": "Aug 7",
    "kind": "Fixed",
    "title": "Nothing on the page is cut off any more",
    "lines": [
      "Text was clipping at some viewport widths across 44 routes, including at wider sizes than ones where the same text fitted.",
      "The detector that had reported them all clean was keyed to the wrong CSS property; it now catches what it had been missing."
    ]
  },
  {
    "date": "2026-08-05",
    "month": "August 2026",
    "label": "Aug 5",
    "kind": "New",
    "title": "The public site, rebuilt on one design system",
    "lines": [
      "One token set, one type scale and one breakpoint system replace 400 colour literals, eleven body-text sizes and seven competing schemes that made neighbouring sections disagree about when to stack.",
      "Light, grey and dark are built from the theme rather than patched onto a light design, and the site is positioned around what it is: the AI business operating system."
    ],
    "more": "/product"
  }
];
