/* GENERATED by scripts/build-content.js — do not edit.
 * Source: src/content/posts/*.md
 */

import type { Post, PostMeta } from './types';

export const POSTS: Post[] = [
  {
    "slug": "rebuilt-not-redesigned",
    "title": "We rebuilt the site instead of redesigning it",
    "description": "The previous pass ended with 400 colour literals, eleven body-text sizes and seven competing breakpoint systems. Neighbouring sections disagreed about when to stack.",
    "topic": "Behind the build",
    "tone": "brand",
    "date": "2026-08-09",
    "readMinutes": 4,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/guide-playbook-spread",
    "artAlt": "A design system laid out as a set of measured pages",
    "takeaways": [
      "Four hundred colour literals and seven breakpoint systems is not a styling problem, it is an absence of a system.",
      "Connectors drawn between measured nodes survive a resize; fixed-width dashed borders do not.",
      "Thirty-eight decorations placed by eye all landed on live copy, one of them 78 pixels deep.",
      "A detector keyed to the wrong CSS property reported a clean sweep on a page full of clipped text."
    ],
    "blocks": [
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The honest summary of the previous site is that it looked fine and could not be changed safely."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Four hundred colour literals. Eleven distinct body-text sizes. Seven competing breakpoint schemes, which meant two sections next to each other genuinely disagreed about the width at which they should stack — and both were right, because each had its own definition."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "That is not a tidiness complaint. It is what a design system's absence looks like from the inside: every change is local, no change is safe, and the only way to know whether you broke something is to look at all of it."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "What replaced it",
        "id": "what-replaced-it"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Three rules, and everything else follows from them."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "strong",
            "v": "Every colour, size and threshold comes from one module."
          },
          {
            "t": "text",
            "v": " A section that invents its own is a bug even when it looks right, because looking right today is how you get four hundred literals. One token set, one type scale, one breakpoint hook."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "strong",
            "v": "Every breakpoint is designed, not derived."
          },
          {
            "t": "text",
            "v": " Write the layout each width actually needs. Do not stack a mobile override on a desktop rule and hope the cascade resolves it — that is how you end up with text that ellipsizes at a "
          },
          {
            "t": "em",
            "v": "wider"
          },
          {
            "t": "text",
            "v": " viewport than one where it fits, which sounds impossible until you meet it."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "strong",
            "v": "Motion is decoration, never load-bearing."
          },
          {
            "t": "text",
            "v": " Every animated element renders in its finished state and only hides itself afterwards, on the client. The page is complete with JavaScript disabled and with reduced motion set, because those are real visitors, and because a crawler that does not run scripts should still see the words."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Illustrations are measured, not faked",
        "id": "illustrations-are-measured-not-faked"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The diagrams on the site draw connectors between nodes. The tempting way to build one is a dashed border of a fixed width and a text arrow — it takes ten minutes and looks correct in the design."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "It detaches the moment anything resizes. Different font, different language, different zoom: the wire now ends in empty space next to the box it was pointing at."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "So connectors are real geometry. The overlay measures the actual nodes and draws between the coordinates it gets back. This costs more, and it comes with a rule worth writing on the wall:"
          }
        ]
      },
      {
        "kind": "callout",
        "tone": "brand",
        "text": [
          {
            "t": "text",
            "v": "Never place a transform between the connector surface and the nodes it measures. Measurement includes transforms, so a per-tile reveal animation or a scale on a wrapper detaches every wire at once."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The thirty-eight illustrations that sat on the copy",
        "id": "the-thirty-eight-illustrations-that-sat-on-the-copy"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "We have a component that puts an illustration into empty space inside a section. The first placement pass was done the reasonable way: look at the layout, notice the heading column is narrow, conclude the right side is free."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Thirty-eight placements were made that way. Every one of them landed on live text — by 78 pixels in the worst case."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The layout "
          },
          {
            "t": "em",
            "v": "looks"
          },
          {
            "t": "text",
            "v": " like it has a hole. It does not have one at the width you support least. A gap that is 620 by 200 at 1440 is smaller at 1120, and the illustration does not know that."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Now a placement is only allowed where a hole has been rasterised and measured, at the tightest width, and a page with no hole gets no illustration. That last part was the hard bit to accept: a page with nowhere to put a decoration is finished, not unfinished. Adding whitespace to a working layout so a drawing has somewhere to live is backwards."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The detector that was confidently wrong",
        "id": "the-detector-that-was-confidently-wrong"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Because looking at every page at every width in every theme is not something a person does reliably, we wrote detectors: scripts that intersect every decoration with every text run and image, and every decoration with every other one."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The first version of the clipped-text detector reported a clean sweep. The page it swept was full of cut text."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "code",
            "v": "numberOfLines"
          },
          {
            "t": "text",
            "v": " compiles to "
          },
          {
            "t": "code",
            "v": "-webkit-line-clamp"
          },
          {
            "t": "text",
            "v": " and "
          },
          {
            "t": "code",
            "v": "overflow: hidden"
          },
          {
            "t": "text",
            "v": " — "
          },
          {
            "t": "strong",
            "v": "not"
          },
          {
            "t": "text",
            "v": " "
          },
          {
            "t": "code",
            "v": "text-overflow: ellipsis"
          },
          {
            "t": "text",
            "v": ". The detector was keyed to "
          },
          {
            "t": "code",
            "v": "text-overflow"
          },
          {
            "t": "text",
            "v": ", so it looked for a property that was never going to be set and found nothing, which it reported as success."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "There is a second one in the same family: a count-up animation runs for about 1.2 seconds after a statistic scrolls into view, so anything measured before it settles reports phantom overflow on every animated number on the page."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "A detector that reports success is not evidence. A detector that has been shown a known failure and caught it is evidence. We now start by breaking the page on purpose."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Why a clean room, and not an evolution",
        "id": "why-a-clean-room-and-not-an-evolution"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The V5 site does not import, adapt or link to anything from the previous system, in either direction, and that is enforced rather than encouraged."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Sharing \"just the logic\" is how the old conventions travel. One import brings a component; the component brings a colour literal; the literal brings the assumption that there is one theme. If something genuinely needs to exist in both, we write it twice, deliberately, and accept the duplication as the price of not coupling two products with separate release paths."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The rule we actually check work against is simpler than any of this, and it is the one most often skipped:"
          }
        ]
      },
      {
        "kind": "quote",
        "text": [
          {
            "t": "text",
            "v": "Nothing is done until it has been looked at. Type-checking is not validation. Build it, screenshot it, and open the image."
          }
        ]
      }
    ]
  },
  {
    "slug": "three-themes-and-unreadable-white",
    "title": "Three themes, and the day white text stopped being readable",
    "description": "Our accents get lighter in the dark themes so they read against the page. That decision pushed the white label on every button below the accessibility floor.",
    "topic": "Design systems",
    "tone": "violet",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/blog-three-themes",
    "artAlt": "One interface shown in a light, a grey and a dark palette side by side",
    "takeaways": [
      "A theme is not a colour swap; an accent lightened to work on a dark page stops being able to carry white text.",
      "White on our accent measured between 2.0 and 2.9 to 1 in the dark themes, under even the 3:1 floor for large text.",
      "Inverting a single ink token fixed roughly 44 call sites without any of them being edited.",
      "Build the stylesheet from the theme rather than patching a light one, or this class of bug keeps returning."
    ],
    "blocks": [
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "FlowSmartly ships three themes: light, a neutral charcoal we call "
          },
          {
            "t": "strong",
            "v": "grey"
          },
          {
            "t": "text",
            "v": ", and a near-black navy "
          },
          {
            "t": "strong",
            "v": "dark"
          },
          {
            "t": "text",
            "v": ". Not a light design with a dark mode bolted on — three palettes, all of them shipping states, all of them expected to look deliberate."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "That commitment produced a bug we did not see coming, in the one place nobody thinks to check."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The decision that caused it",
        "id": "the-decision-that-caused-it"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Our brand blue is "
          },
          {
            "t": "code",
            "v": "#0878f9"
          },
          {
            "t": "text",
            "v": ". It is a deep, saturated blue, and it looks right on a white page."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "On a near-black page it does not. A deep blue on a dark ground has almost no separation from the ground — the button stops reading as a button. So the dark palettes raise the accent: "
          },
          {
            "t": "code",
            "v": "brand"
          },
          {
            "t": "text",
            "v": " becomes "
          },
          {
            "t": "code",
            "v": "#4f9dff"
          },
          {
            "t": "text",
            "v": " in grey and dark, a lighter, airier blue that actually reads against a near-black background."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "That is the correct call. It is also the whole problem."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "What it broke",
        "id": "what-it-broke"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Every primary button on the site painted white text on that accent. In light, white on "
          },
          {
            "t": "code",
            "v": "#0878f9"
          },
          {
            "t": "text",
            "v": " is a comfortable pass. In grey and dark, white on "
          },
          {
            "t": "code",
            "v": "#4f9dff"
          },
          {
            "t": "text",
            "v": " measured between "
          },
          {
            "t": "strong",
            "v": "2.0 and 2.9 to 1"
          },
          {
            "t": "text",
            "v": "."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "For context, WCAG asks for 4.5:1 on body text and relaxes to 3:1 for large text. Those numbers are below the relaxed floor. Not marginal — under the line that exists for headlines."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "And it was everywhere. Every "
          },
          {
            "t": "em",
            "v": "Approve"
          },
          {
            "t": "text",
            "v": ", every "
          },
          {
            "t": "em",
            "v": "Accept all"
          },
          {
            "t": "text",
            "v": ", every "
          },
          {
            "t": "em",
            "v": "Pay"
          },
          {
            "t": "text",
            "v": ", every numbered step badge on the site: roughly forty-four call sites, each of them written correctly, each of them assuming the thing that had stopped being true."
          }
        ]
      },
      {
        "kind": "callout",
        "tone": "violet",
        "text": [
          {
            "t": "text",
            "v": "Nothing here was a mistake in isolation. Raising the accent was right. White on the original accent was right. The bug lived in the space between two correct decisions, which is where most theming bugs live."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The fix that was not forty-four fixes",
        "id": "the-fix-that-was-not-forty-four-fixes"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The obvious repair is to walk the call sites and pick a colour per theme at each one. Forty-four edits, forty-four chances to be inconsistent, and a forty-fifth button next month that nobody remembers to check."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Instead we gave the palette a token whose "
          },
          {
            "t": "em",
            "v": "meaning"
          },
          {
            "t": "text",
            "v": " is the answer:"
          }
        ]
      },
      {
        "kind": "quote",
        "text": [
          {
            "t": "code",
            "v": "textOnBrand"
          },
          {
            "t": "text",
            "v": " — ink for anything painted "
          },
          {
            "t": "strong",
            "v": "on"
          },
          {
            "t": "text",
            "v": " a brand or accent fill. It is not \"white\". It is whatever clears 4.5:1 on the fills this particular palette uses."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "In light it stays white, because light's accents are deep. In grey and dark it becomes a dark ink, because those palettes' accents are light. Dark ink on a light fill is simply the correct inversion — and every button already asked for "
          },
          {
            "t": "code",
            "v": "textOnBrand"
          },
          {
            "t": "text",
            "v": ", so all forty-four call sites were fixed without one of them being opened."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The trade is real and worth naming: the gradient tokens now have to stay light enough in grey and dark for dark ink to sit on them. They are background-only tokens, so that costs nothing."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The rule underneath",
        "id": "the-rule-underneath"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The reason this was findable at all is a rule we hold to hard enough to reject work over:"
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "strong",
            "v": "Build the stylesheet from the theme. Never write a light stylesheet and patch it."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Every component takes tokens and returns styles: "
          },
          {
            "t": "code",
            "v": "createStyles(tokens, layout)"
          },
          {
            "t": "text",
            "v": ". No component owns a colour. If it needed a literal, the design system was missing something, and the missing thing is the actual bug."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "A codebase that patches a light design into darkness has no single place where \"what ink goes on an accent fill\" is decided, so the question gets answered forty -four times, and one of those answers stops being true the moment the palette moves."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "We had one place. Which is why this became a one-line change rather than a project."
          }
        ]
      }
    ]
  },
  {
    "slug": "we-deleted-our-own-numbers",
    "title": "We deleted the numbers that made us look successful",
    "description": "A pass through our own marketing site removed a $32M funding round, 120 staff across 22 countries, 25,000 customers and six colleagues. None of them existed.",
    "topic": "Behind the build",
    "tone": "orange",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/press-kit",
    "artAlt": "A press page with most of its claims struck out",
    "takeaways": [
      "A fabricated customer count is checkable, and a named customer is checkable by anyone who searches the name.",
      "Placeholder marketing copy survives because nobody re-reads a page after it ships.",
      "Labelling a figure illustrative works for a product mockup and does not work for a testimonial with a photograph beside it.",
      "We keep the unfinished part of the audit in a file in the repo, so what is left is a decision rather than an oversight."
    ],
    "featured": true,
    "blocks": [
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Our press page used to carry five headlines under the names of real trade publications. One of them announced that FlowSmartly had raised $32 million. Below the headlines sat a fact sheet, marked "
          },
          {
            "t": "em",
            "v": "cleared for publication"
          },
          {
            "t": "text",
            "v": ", giving a founding year, a headquarters, 120 staff across 22 countries, 25,000+ customers and a $48M Series B."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Every number in that paragraph was invented. So were the headlines, and so were the publications' interest in us."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "What was actually on the site",
        "id": "what-was-actually-on-the-site"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The press page was the worst of it, but it was not alone."
          }
        ]
      },
      {
        "kind": "ul",
        "items": [
          [
            {
              "t": "strong",
              "v": "`/company/about`"
            },
            {
              "t": "text",
              "v": " carried a 2019-to-2024 company history and a band of five-figure traction statistics. The company did not do those things in those years."
            }
          ],
          [
            {
              "t": "strong",
              "v": "Leadership"
            },
            {
              "t": "text",
              "v": " showed four colleagues on the about page and two more on the press page, standing beside the one real founder. Six people who do not exist, with portraits and titles."
            }
          ],
          [
            {
              "t": "strong",
              "v": "`/company/customers`"
            },
            {
              "t": "text",
              "v": " — still the largest single concentration — carries eight statistics, three named customer companies with results attached, and three named individuals with photographs and quotes."
            }
          ]
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The history, the traction band, the invented press coverage and the invented colleagues are gone. Both leadership grids are down to the one person who has been confirmed."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Nobody sat down and decided to lie",
        "id": "nobody-sat-down-and-decided-to-lie"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "This is the part worth saying plainly, because it is the part that generalises."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "A design pass needs words in every slot. You are building a press page, so you write what a press page contains: a headline, a publication, a figure. You are building a leadership grid, so you fill the grid. The copy is scaffolding — it exists to prove the layout works, and everyone involved knows it is scaffolding at the moment they write it."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Then the layout ships, and the scaffolding ships with it, and nobody re-reads a page that already looks finished. The gap between \"this is placeholder\" and \"this is a public claim about our company\" is one deploy and about four minutes of attention."
          }
        ]
      },
      {
        "kind": "callout",
        "tone": "orange",
        "text": [
          {
            "t": "text",
            "v": "The tell is specificity. Nobody invents \"some customers\" — invention produces 25,000+, 4.9 out of 5, $1.4B influenced. Placeholder copy is confident, because confident copy is what makes a layout look right."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Why a named customer is worse than a big number",
        "id": "why-a-named-customer-is-worse-than-a-big-number"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "An inflated statistic is dishonest and vague. A named company is dishonest and "
          },
          {
            "t": "strong",
            "v": "checkable"
          },
          {
            "t": "text",
            "v": "."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Anyone who reads a case study and searches for the customer finds nothing. That is not a small credibility problem discovered by a diligent minority — it is the exact behaviour of the one visitor you most want, the one who is far enough down the funnel to verify a claim before bringing it to their boss."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The same goes double for a person. A stock portrait, a name, a job title and a sentence in quotation marks is a fabricated testimonial. It stays a fabricated testimonial no matter what disclaimer sits under it."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The rule we ended up with",
        "id": "the-rule-we-ended-up-with"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The site already had a convention for uncertain figures, and it works: "
          },
          {
            "t": "code",
            "v": "/status"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "/solutions/domains"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "/solutions/video-studio"
          },
          {
            "t": "text",
            "v": " and the footer all mark their numbers "
          },
          {
            "t": "strong",
            "v": "illustrative"
          },
          {
            "t": "text",
            "v": ". A product mockup showing a dashboard needs numbers in it, and saying so is honest and sufficient."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "What we learned is where that convention stops:"
          }
        ]
      },
      {
        "kind": "ol",
        "items": [
          [
            {
              "t": "strong",
              "v": "A mockup can be illustrative."
            },
            {
              "t": "text",
              "v": " It is a drawing of software, and the figures in it are obviously a sample."
            }
          ],
          [
            {
              "t": "strong",
              "v": "A statistic about the business cannot be."
            },
            {
              "t": "text",
              "v": " \"25,000 customers (illustrative)\" is not a disclosure, it is a sentence that has given up."
            }
          ],
          [
            {
              "t": "strong",
              "v": "A person can never be."
            },
            {
              "t": "text",
              "v": " A photograph with a name and a quote is a claim about a human being, and a label underneath does not unmake it."
            }
          ]
        ]
      },
      {
        "kind": "h2",
        "text": "What is still on the list",
        "id": "what-is-still-on-the-list"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The audit is not finished. "
          },
          {
            "t": "code",
            "v": "/company/customers"
          },
          {
            "t": "text",
            "v": " is still standing, and the scattered testimonials on the product pages are still there."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Both are recorded, in the repository, in a file that exists so that anything left undone is a decision somebody made rather than something everybody forgot. The options are written down next to each entry: rebuild the page as an honest early-stage page, take it down until there is a real customer to feature, or label it and accept that labelling does not fix the portraits."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "We would rather publish that the list is unfinished than publish a page implying it never existed. A company with no customer numbers yet is an early company. A company with invented ones is a different kind of company entirely, and the difference is worth more than the numbers were."
          }
        ]
      }
    ]
  },
  {
    "slug": "we-let-the-ai-crawlers-in",
    "title": "We let the AI crawlers in, and blocked the ones that don't cite",
    "description": "Most sites are choosing between allowing every AI crawler and blocking all of them. Neither is the interesting option. The line worth drawing is attribution.",
    "topic": "AI visibility",
    "tone": "green",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/blog-ai-conversations",
    "artAlt": "An assistant answering a question and naming its source",
    "takeaways": [
      "Blocking every AI crawler also blocks the ones that send visitors and name their sources.",
      "The useful line is not AI versus no AI, it is engines that cite versus scrapers that do not.",
      "robots.txt grants the permission, ai.txt states the terms, and llms.txt is the summary an assistant can read in one request.",
      "Being cited well is a distribution channel, and it rewards page-level structure rather than clever copy."
    ],
    "blocks": [
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "There is a default forming on the web where a site either allows every AI crawler or blocks all of them, and both defaults are lazy."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Our "
          },
          {
            "t": "code",
            "v": "robots.txt"
          },
          {
            "t": "text",
            "v": " names the crawlers individually, and the line it draws is not about AI at all."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "The list",
        "id": "the-list"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Explicitly allowed: "
          },
          {
            "t": "code",
            "v": "OAI-SearchBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "ChatGPT-User"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "GPTBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "ClaudeBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Claude-User"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Claude-SearchBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "PerplexityBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Perplexity-User"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Google-Extended"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Applebot-Extended"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Bingbot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "DuckDuckBot"
          },
          {
            "t": "text",
            "v": "."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Explicitly disallowed: "
          },
          {
            "t": "code",
            "v": "CCBot"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Bytespider"
          },
          {
            "t": "text",
            "v": ", "
          },
          {
            "t": "code",
            "v": "Omgilibot"
          },
          {
            "t": "text",
            "v": "."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The comment in the file explains the split better than a policy page would:"
          }
        ]
      },
      {
        "kind": "quote",
        "text": [
          {
            "t": "text",
            "v": "Bulk training scrapers that neither cite nor refer traffic. Not a judgement on AI — a judgement on attribution."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Why blocking them all is the expensive option",
        "id": "why-blocking-them-all-is-the-expensive-option"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "An answer engine is a referrer. When somebody asks an assistant which platform handles a job, and the assistant names three and links them, that is the same event as ranking on a results page — the surface changed, the mechanism did not."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Blocking those crawlers removes you from that answer. It does not protect you from anything, because the engines that ignore consent were never going to respect the file. You have declined the visitors and kept the exposure."
          }
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "The crawlers worth refusing are the ones that take the page and return nothing: no link, no name, no visitor. That is not a philosophical objection to machine reading. It is the same deal every publisher has always had with every index — you may read this if you say where it came from."
          }
        ]
      },
      {
        "kind": "callout",
        "tone": "green",
        "text": [
          {
            "t": "text",
            "v": "The practical version, for a young site: search engines rank you against fifteen years of somebody else's backlinks. Answer engines assemble a response from what they can read "
          },
          {
            "t": "em",
            "v": "right now"
          },
          {
            "t": "text",
            "v": ". That asymmetry favours you, and only if they can read you."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "Three files, three jobs",
        "id": "three-files-three-jobs"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "They get confused with each other constantly, so:"
          }
        ]
      },
      {
        "kind": "ul",
        "items": [
          [
            {
              "t": "strong",
              "v": "`robots.txt`"
            },
            {
              "t": "text",
              "v": " is permission. Which agents may fetch which paths. It is a door, and it answers exactly one question."
            }
          ],
          [
            {
              "t": "strong",
              "v": "`ai.txt`"
            },
            {
              "t": "text",
              "v": " is terms. Ours permits reading, indexing, summarising, quoting with attribution and answering user questions, and denies bulk training without attribution, verbatim republication and anything presented as an official communication from us. It sets "
            },
            {
              "t": "code",
              "v": "Attribution-Required: yes"
            },
            {
              "t": "text",
              "v": " and "
            },
            {
              "t": "code",
              "v": "Preferred-Citation: page-level"
            },
            {
              "t": "text",
              "v": " — cite the page that makes the claim, not a summary of the site."
            }
          ],
          [
            {
              "t": "strong",
              "v": "`llms.txt`"
            },
            {
              "t": "text",
              "v": " is the summary. One document that describes what is here and where, so an assistant can understand the site in a single request instead of crawling forty pages and guessing."
            }
          ]
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Ours is generated from the export itself, by a script that walks the built output and writes down the routes that actually shipped. A hand-maintained summary starts drifting from the site the week after someone writes it."
          }
        ]
      },
      {
        "kind": "h2",
        "text": "What being citable actually takes",
        "id": "what-being-citable-actually-takes"
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "Once they are allowed in, the question stops being access and becomes whether your page is "
          },
          {
            "t": "em",
            "v": "quotable"
          },
          {
            "t": "text",
            "v": ". Assistants lift spans. Give them clean spans."
          }
        ]
      },
      {
        "kind": "ol",
        "items": [
          [
            {
              "t": "strong",
              "v": "Answer the question in the heading."
            },
            {
              "t": "text",
              "v": " A heading that names the question gets matched to the question. A clever one does not."
            }
          ],
          [
            {
              "t": "strong",
              "v": "State conclusions in complete sentences."
            },
            {
              "t": "text",
              "v": " A claim that depends on the two paragraphs above it cannot be lifted, so it will not be."
            }
          ],
          [
            {
              "t": "strong",
              "v": "Structure over voice."
            },
            {
              "t": "text",
              "v": " Definitions, numbered steps, comparison tables and a real FAQ get extracted. Flowing prose gets skipped."
            }
          ],
          [
            {
              "t": "strong",
              "v": "Publish dates and keep them accurate."
            },
            {
              "t": "text",
              "v": " Freshness is an input, and a page that lies about it gets treated accordingly."
            }
          ],
          [
            {
              "t": "strong",
              "v": "Say the specific thing."
            },
            {
              "t": "text",
              "v": " \"Improve your visibility\" matches nothing. \"How a single-location business appears in the map pack\" matches a real question somebody is really asking."
            }
          ]
        ]
      },
      {
        "kind": "p",
        "text": [
          {
            "t": "text",
            "v": "None of that is a trick. It is the same page, written so the useful part can be found without reading all of it — which, it turns out, human readers also wanted."
          }
        ]
      }
    ]
  }
];

/** Index metadata without the bodies — what the archive page renders. */
export const POST_INDEX: PostMeta[] = [
  {
    "slug": "rebuilt-not-redesigned",
    "title": "We rebuilt the site instead of redesigning it",
    "description": "The previous pass ended with 400 colour literals, eleven body-text sizes and seven competing breakpoint systems. Neighbouring sections disagreed about when to stack.",
    "topic": "Behind the build",
    "tone": "brand",
    "date": "2026-08-09",
    "readMinutes": 4,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/guide-playbook-spread",
    "artAlt": "A design system laid out as a set of measured pages",
    "takeaways": [
      "Four hundred colour literals and seven breakpoint systems is not a styling problem, it is an absence of a system.",
      "Connectors drawn between measured nodes survive a resize; fixed-width dashed borders do not.",
      "Thirty-eight decorations placed by eye all landed on live copy, one of them 78 pixels deep.",
      "A detector keyed to the wrong CSS property reported a clean sweep on a page full of clipped text."
    ]
  },
  {
    "slug": "three-themes-and-unreadable-white",
    "title": "Three themes, and the day white text stopped being readable",
    "description": "Our accents get lighter in the dark themes so they read against the page. That decision pushed the white label on every button below the accessibility floor.",
    "topic": "Design systems",
    "tone": "violet",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/blog-three-themes",
    "artAlt": "One interface shown in a light, a grey and a dark palette side by side",
    "takeaways": [
      "A theme is not a colour swap; an accent lightened to work on a dark page stops being able to carry white text.",
      "White on our accent measured between 2.0 and 2.9 to 1 in the dark themes, under even the 3:1 floor for large text.",
      "Inverting a single ink token fixed roughly 44 call sites without any of them being edited.",
      "Build the stylesheet from the theme rather than patching a light one, or this class of bug keeps returning."
    ]
  },
  {
    "slug": "we-deleted-our-own-numbers",
    "title": "We deleted the numbers that made us look successful",
    "description": "A pass through our own marketing site removed a $32M funding round, 120 staff across 22 countries, 25,000 customers and six colleagues. None of them existed.",
    "topic": "Behind the build",
    "tone": "orange",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/press-kit",
    "artAlt": "A press page with most of its claims struck out",
    "takeaways": [
      "A fabricated customer count is checkable, and a named customer is checkable by anyone who searches the name.",
      "Placeholder marketing copy survives because nobody re-reads a page after it ships.",
      "Labelling a figure illustrative works for a product mockup and does not work for a testimonial with a photograph beside it.",
      "We keep the unfinished part of the audit in a file in the repo, so what is left is a decision rather than an oversight."
    ],
    "featured": true
  },
  {
    "slug": "we-let-the-ai-crawlers-in",
    "title": "We let the AI crawlers in, and blocked the ones that don't cite",
    "description": "Most sites are choosing between allowing every AI crawler and blocking all of them. Neither is the interesting option. The line worth drawing is attribution.",
    "topic": "AI visibility",
    "tone": "green",
    "date": "2026-08-09",
    "readMinutes": 3,
    "author": "Jean-Yves Koffi",
    "authorRole": "Co-founder & CEO, FlowSmartly",
    "authorAvatar": "people/jean-yves-koffi",
    "art": "editorial/blog-ai-conversations",
    "artAlt": "An assistant answering a question and naming its source",
    "takeaways": [
      "Blocking every AI crawler also blocks the ones that send visitors and name their sources.",
      "The useful line is not AI versus no AI, it is engines that cite versus scrapers that do not.",
      "robots.txt grants the permission, ai.txt states the terms, and llms.txt is the summary an assistant can read in one request.",
      "Being cited well is a distribution channel, and it rewards page-level structure rather than clever copy."
    ]
  }
];

export const TOPICS: string[] = ["Behind the build","Design systems","AI visibility"];

export function postBySlug(slug: string): Post | undefined {
  return POSTS.find((post) => post.slug === slug);
}
