/**
 * The DESIGN STYLE LIBRARY — every visual "look" the canvas (Design studio &
 * Print studio) can render. A style is pure data: a background, the text inks,
 * and an optional decorative frame. The token `@accent` anywhere in a color/bg
 * is replaced with the design's brand accent at render time, so styles stay
 * brand-aware. Keep styles VISUALLY DISTINCT and high-contrast.
 *
 * Add new styles by appending to DESIGN_STYLES (large library is intentional —
 * grouped by `category` in the Style tab). The 6 "classic" keys (modern,
 * minimalist, photorealistic, bold, elegant, playful) must stay so older saved
 * designs keep resolving. [[design-canvas-progress]]
 */

export interface StyleFrame {
  /** px inset of the frame line from the poster edge. */
  inset?: number;
  /** CSS border, e.g. "1px solid rgba(255,255,255,0.25)" (may use @accent). */
  border?: string;
  /** corner radius of the frame line. */
  radius?: number;
  /** an optional SECOND, inner line a few px further in. */
  innerBorder?: string;
  innerInset?: number;
}

export interface StyleDef {
  key: string;
  label: string;
  /** 2–4 word descriptor shown under the label. */
  desc: string;
  /** grouping shown as a section header in the Style tab. */
  category: string;
  /** CSS background value — solids, gradients, or layered gradients. May use @accent. */
  bg: string;
  /** Optional real bitmap background asset generated by the image model. */
  bgImage?: string;
  headInk: string;
  subInk: string;
  eyeInk: string;
  serif?: boolean;
  /** a brand-accent radial glow overlay behind the design. */
  glow?: boolean;
  frame?: StyleFrame;
}

export interface ResolvedStyle {
  bg: string;
  bgImage?: string;
  headInk: string;
  subInk: string;
  eyeInk: string;
  serif: boolean;
  glow: boolean;
  frame?: StyleFrame;
}

// The 6 classics (kept for back-compat) — the rest of the library is appended.
const CLASSIC_STYLES: StyleDef[] = [
  { key: "modern", label: "Modern", desc: "AI swoosh frame", category: "Modern & Tech", bg: "#f8fafc", bgImage: "/design-backgrounds/frame-corporate-swoosh.png", headInk: "#0f172a", subInk: "#334155", eyeInk: "#0f766e" },
  { key: "photorealistic", label: "Photo", desc: "AI glass backdrop", category: "Modern & Tech", bg: "#06111f", bgImage: "/design-backgrounds/frame-glass-tech.png", headInk: "#ffffff", subInk: "rgba(225,240,255,0.86)", eyeInk: "#67e8f9", glow: false },
  { key: "minimalist", label: "Minimal", desc: "White space, thin type", category: "Editorial & Minimal", bg: "#f6f6f4", headInk: "#0a0a0a", subInk: "#3f3f46", eyeInk: "#71717a" },
  { key: "bold", label: "Bold", desc: "High-contrast, huge type", category: "Bold & Impact", bg: "linear-gradient(160deg,#0a0a0a,#000000)", headInk: "#ffffff", subInk: "rgba(255,255,255,0.82)", eyeInk: "@accent", glow: true },
  { key: "elegant", label: "Elegant", desc: "AI luxury frame", category: "Luxury & Elegant", bg: "#101010", bgImage: "/design-backgrounds/frame-luxury-editorial.png", headInk: "#f5e9d0", subInk: "rgba(245,233,208,0.82)", eyeInk: "#eccb93", serif: true },
  { key: "playful", label: "Playful", desc: "AI creator frame", category: "Playful & Vibrant", bg: "#fff7ed", bgImage: "/design-backgrounds/frame-vibrant-creator.png", headInk: "#1f2937", subInk: "#475569", eyeInk: "#ec4899" },
];

// Extra styles authored as a large library (appended below CLASSIC_STYLES).
export const EXTRA_STYLES: StyleDef[] = [
  // ── Modern & Tech / Corporate ──────────────────────────────────────────
  { key: "mt-aurora-mesh", label: "Aurora Mesh", desc: "Layered neon mesh", category: "Modern & Tech", bg: "radial-gradient(80% 62% at 18% 12%, @accent, transparent 54%), radial-gradient(58% 50% at 86% 22%, #a855f766, transparent 58%), radial-gradient(85% 72% at 54% 104%, #22d3ee66, transparent 60%), conic-gradient(from 210deg at 50% 48%,#111827,#1e1b4b,#052e46,#111827)", headInk: "#f5f7ff", subInk: "#c4ccdf", eyeInk: "@accent", glow: true },
  { key: "mt-glass-vault", label: "Glass Vault", desc: "AI glass frame", category: "Modern & Tech", bg: "#06111f", bgImage: "/design-backgrounds/frame-glass-tech.png", headInk: "#eef2fb", subInk: "#aab4cc", eyeInk: "#67e8f9", glow: false },
  { key: "mt-violet-haze", label: "Violet Haze", desc: "Editorial violet glow", category: "Modern & Tech", bg: "radial-gradient(120% 74% at 52% -8%, #c084fc88, transparent 58%), radial-gradient(42% 42% at 16% 80%, @accent, transparent 64%), linear-gradient(180deg,#1b0f35 0%,#100820 58%,#070411 100%)", headInk: "#f6f2ff", subInk: "#c9bce4", eyeInk: "#d8c8ff", glow: false },
  { key: "mt-neon-grid", label: "Neon Grid", desc: "Cyber line system", category: "Modern & Tech", bg: "linear-gradient(rgba(14,165,233,.12) 1px, transparent 1px), linear-gradient(90deg,rgba(14,165,233,.12) 1px, transparent 1px), radial-gradient(90% 70% at 100% 0%, @accent, transparent 55%), linear-gradient(200deg,#071018,#03070c)", headInk: "#eafff8", subInk: "#9fc7bd", eyeInk: "@accent", glow: true, frame: { inset: 12, border: "1px solid @accent", radius: 6 } },
  { key: "mt-midnight-fade", label: "Midnight Fade", desc: "Split dark product", category: "Modern & Tech", bg: "linear-gradient(105deg,#0f172a 0 52%, transparent 52%), radial-gradient(90% 70% at 85% 26%, #334155 0%,#111827 46%,#020617 100%)", headInk: "#f1f5f9", subInk: "#b4c0d3", eyeInk: "@accent" },
  { key: "mt-education-frame", label: "Education", desc: "AI school border", category: "Modern & Tech", bg: "#fffaf0", bgImage: "/design-backgrounds/frame-education-border.png", headInk: "#111827", subInk: "#475569", eyeInk: "#0ea5e9" },
  { key: "frame-swoosh-left", label: "Swoosh Left", desc: "AI left-side frame", category: "Generated Frames", bg: "#f8fafc", bgImage: "/design-backgrounds/frame-corporate-swoosh-left.png", headInk: "#0f172a", subInk: "#334155", eyeInk: "#0f766e" },
  { key: "frame-swoosh-top", label: "Swoosh Top", desc: "AI top frame", category: "Generated Frames", bg: "#f8fafc", bgImage: "/design-backgrounds/frame-corporate-swoosh-top.png", headInk: "#0f172a", subInk: "#334155", eyeInk: "#0f766e" },
  { key: "frame-swoosh-bottom", label: "Swoosh Bottom", desc: "AI bottom frame", category: "Generated Frames", bg: "#f8fafc", bgImage: "/design-backgrounds/frame-corporate-swoosh-bottom.png", headInk: "#0f172a", subInk: "#334155", eyeInk: "#0f766e" },
  { key: "frame-luxury-left", label: "Emerald Left", desc: "AI emerald gold", category: "Generated Frames", bg: "#fbf8ef", bgImage: "/design-backgrounds/frame-luxury-left-emerald.png", headInk: "#13251e", subInk: "#475569", eyeInk: "#b88a2b", serif: true },
  { key: "frame-neon-top", label: "Violet Top", desc: "AI glass neon", category: "Generated Frames", bg: "#f6f0ff", bgImage: "/design-backgrounds/frame-neon-top-violet.png", headInk: "#1f1147", subInk: "#4b5563", eyeInk: "#7c3aed" },
  { key: "frame-paper-bottom", label: "Paper Bottom", desc: "AI warm paper", category: "Generated Frames", bg: "#fff8f1", bgImage: "/design-backgrounds/frame-paper-bottom-terracotta.png", headInk: "#3a2419", subInk: "#6b4b3c", eyeInk: "#b4532a", serif: true },
  { key: "frame-creator-right", label: "Creator Right", desc: "AI colorful frame", category: "Generated Frames", bg: "#fffaf2", bgImage: "/design-backgrounds/frame-creator-right-color.png", headInk: "#172033", subInk: "#475569", eyeInk: "#ec4899" },
  { key: "corp-clean-slate", label: "Clean Slate", desc: "Trustworthy light slate", category: "Corporate", bg: "linear-gradient(180deg,#ffffff,#f1f5f9)", headInk: "#0f172a", subInk: "#475569", eyeInk: "@accent", frame: { inset: 16, border: "1px solid #e2e8f0", radius: 4 } },
  { key: "corp-navy-authority", label: "Navy Authority", desc: "Bold professional navy", category: "Corporate", bg: "linear-gradient(160deg,#0f2444,#0a1b34)", headInk: "#f8fafc", subInk: "#bcccdf", eyeInk: "@accent", serif: true, frame: { inset: 18, border: "1px solid #ffffff26", radius: 2 } },
  { key: "corp-ivory-rule", label: "Ivory Rule", desc: "Refined serif ivory", category: "Corporate", bg: "linear-gradient(180deg,#fdfcf9,#f4f1ea)", headInk: "#1c2533", subInk: "#5a6472", eyeInk: "@accent", serif: true, frame: { inset: 16, border: "1px solid #d9d4c7", radius: 3, innerBorder: "1px solid @accent", innerInset: 5 } },
  { key: "corp-steel-mist", label: "Steel Mist", desc: "Cool structured grey", category: "Corporate", bg: "radial-gradient(120% 90% at 50% 0%, #ffffff, transparent 55%), linear-gradient(180deg,#eef2f6,#dde4ec)", headInk: "#1f2a3a", subInk: "#566175", eyeInk: "@accent" },

  // ── Editorial & Minimal / Mono & Type ──────────────────────────────────
  { key: "ed-gallery-white", label: "Gallery White", desc: "Pure museum wall", category: "Editorial & Minimal", bg: "#fafafa", headInk: "#111111", subInk: "#52525b", eyeInk: "@accent", serif: true, frame: { inset: 20, border: "1px solid rgba(0,0,0,0.16)", radius: 0 } },
  { key: "ed-warm-cream", label: "Warm Cream", desc: "Soft paper warmth", category: "Editorial & Minimal", bg: "linear-gradient(180deg, #f7f4ed 0%, #f1ece1 100%)", headInk: "#1a1814", subInk: "#5c554a", eyeInk: "@accent", serif: true, frame: { inset: 18, border: "1px solid rgba(0,0,0,0.14)", radius: 0, innerBorder: "1px solid rgba(0,0,0,0.08)", innerInset: 24 } },
  { key: "ed-cool-paper", label: "Cool Paper", desc: "Crisp cool stock", category: "Editorial & Minimal", bg: "linear-gradient(180deg, #f7f8fa 0%, #eef1f4 100%)", headInk: "#16181d", subInk: "#565d68", eyeInk: "@accent", frame: { inset: 22, border: "1px solid rgba(0,0,0,0.12)", radius: 2 } },
  { key: "ed-hairline-folio", label: "Hairline Folio", desc: "Double-rule margin", category: "Editorial & Minimal", bg: "#f5f3ee", headInk: "#18181b", subInk: "#52525b", eyeInk: "@accent", serif: true, frame: { inset: 16, border: "1px solid @accent", radius: 0, innerBorder: "1px solid rgba(0,0,0,0.10)", innerInset: 22 } },
  { key: "ed-vellum-glow", label: "Vellum", desc: "Luminous off-white", category: "Editorial & Minimal", bg: "radial-gradient(120% 90% at 50% 0%, #ffffff 0%, #f4f2ec 100%)", headInk: "#1c1a17", subInk: "#5a544b", eyeInk: "@accent", serif: true },
  { key: "ed-accent-line", label: "Accent Line", desc: "Single brand rule", category: "Editorial & Minimal", bg: "#f9f9f7", headInk: "#141414", subInk: "#555555", eyeInk: "@accent", frame: { inset: 20, border: "2px solid @accent", radius: 0 } },
  { key: "mono-stark-black", label: "Stark Black", desc: "White on black", category: "Mono & Type", bg: "#0c0c0d", headInk: "#fafafa", subInk: "#a1a1aa", eyeInk: "@accent", frame: { inset: 18, border: "1px solid rgba(255,255,255,0.18)", radius: 0 } },
  { key: "mono-swiss-grid", label: "Swiss Grid", desc: "Black on white", category: "Mono & Type", bg: "#ffffff", headInk: "#000000", subInk: "#3f3f46", eyeInk: "@accent", frame: { inset: 16, border: "1px solid #000000", radius: 0 } },
  { key: "mono-ink-slab", label: "Ink Slab", desc: "Bold type-led", category: "Mono & Type", bg: "linear-gradient(180deg, #141416 0%, #18181b 100%)", headInk: "#f4f4f5", subInk: "#9ca3af", eyeInk: "@accent", glow: true },

  // ── Bold & Impact / Neon & Cyber ───────────────────────────────────────
  { key: "bold-accent-slab", label: "Accent Slab", desc: "Full saturated field", category: "Bold & Impact", bg: "@accent", headInk: "#ffffff", subInk: "#ffffff", eyeInk: "#0a0a0a" },
  { key: "bold-ink-block", label: "Ink Block", desc: "Black & white extreme", category: "Bold & Impact", bg: "#0a0a0a", headInk: "#ffffff", subInk: "#d4d4d4", eyeInk: "@accent", frame: { inset: 0, border: "6px solid @accent", radius: 0 } },
  { key: "bold-split-diagonal", label: "Split Diagonal", desc: "Hard-stop color clash", category: "Bold & Impact", bg: "linear-gradient(110deg,@accent 0 50%, #0a0a0a 50% 100%)", headInk: "#ffffff", subInk: "#ffffff", eyeInk: "#ffffff" },
  { key: "bold-half-stack", label: "Half Stack", desc: "Two-tone horizontal", category: "Bold & Impact", bg: "linear-gradient(180deg,#111111 0 55%, @accent 55% 100%)", headInk: "#ffffff", subInk: "#0a0a0a", eyeInk: "@accent", serif: true },
  { key: "bold-paper-accent", label: "Paper Punch", desc: "White ground bold ink", category: "Bold & Impact", bg: "#ffffff", headInk: "#0a0a0a", subInk: "#333333", eyeInk: "@accent", serif: true, frame: { inset: 0, border: "10px solid @accent", radius: 0 } },
  { key: "neon-synthwave", label: "Synthwave", desc: "Retro horizon glow", category: "Neon & Cyber", bg: "linear-gradient(180deg,#0d0221 0%, #2a0a4a 55%, @accent 100%)", headInk: "#ff5edb", subInk: "#9b8cff", eyeInk: "#00f0ff", glow: true },
  { key: "neon-grid-noir", label: "Grid Noir", desc: "Dark cyber accent", category: "Neon & Cyber", bg: "radial-gradient(120% 90% at 50% 0%, #14142b 0%, #05050a 70%)", headInk: "#ffffff", subInk: "#7de3ff", eyeInk: "@accent", glow: true, frame: { inset: 0, border: "1px solid @accent", radius: 8 } },
  { key: "neon-electric-glow", label: "Electric Glow", desc: "Neon accent on black", category: "Neon & Cyber", bg: "radial-gradient(100% 100% at 50% 120%, @accent 0%, #0a0a0a 60%)", headInk: "#ffffff", subInk: "#cfd8ff", eyeInk: "@accent", glow: true },
  { key: "neon-cyber-frame", label: "Cyber Frame", desc: "Outlined neon edge", category: "Neon & Cyber", bg: "linear-gradient(135deg,#0a0a12 0 60%, #1a0a2e 60% 100%)", headInk: "#39ff14", subInk: "#b8ffd9", eyeInk: "#ff2bd6", glow: true, frame: { inset: 6, border: "1px solid @accent", radius: 4, innerBorder: "1px solid #39ff14", innerInset: 10 } },

  // ── Luxury & Elegant / Dark Premium ────────────────────────────────────
  { key: "lux-emerald-royale", label: "Emerald Royale", desc: "Deep jewel emerald", category: "Luxury & Elegant", bg: "linear-gradient(160deg,#10231b 0%,#0a1a14 55%,#06120d 100%)", headInk: "#e8d9a8", subInk: "#cbbf9a", eyeInk: "#a8c2a0", serif: true, frame: { inset: 14, border: "1px solid #e8d9a8", radius: 2, innerBorder: "1px solid rgba(232,217,168,0.4)", innerInset: 20 } },
  { key: "lux-burgundy-velvet", label: "Burgundy Velvet", desc: "Rich wine burgundy", category: "Luxury & Elegant", bg: "linear-gradient(155deg,#3a0f1c 0%,#250912 60%,#160508 100%)", headInk: "#f5e9d0", subInk: "#e0c9a6", eyeInk: "#eccb93", serif: true, frame: { inset: 14, border: "1px solid #eccb93", radius: 2, innerBorder: "1px solid rgba(236,203,147,0.38)", innerInset: 20 } },
  { key: "lux-midnight-navy", label: "Midnight Navy", desc: "Deep navy gold", category: "Luxury & Elegant", bg: "linear-gradient(165deg,#12203a 0%,#0c1628 58%,#070d18 100%)", headInk: "#eccb93", subInk: "#cdd6e6", eyeInk: "#d9b876", serif: true, glow: true, frame: { inset: 16, border: "1px solid #eccb93", radius: 2, innerBorder: "1px solid rgba(236,203,147,0.35)", innerInset: 22 } },
  { key: "lux-charcoal-gilt", label: "Charcoal Gilt", desc: "Charcoal warm gold", category: "Luxury & Elegant", bg: "linear-gradient(160deg,#2a2622 0%,#1c1916 55%,#110f0d 100%)", headInk: "#e8d9a8", subInk: "#c8bfac", eyeInk: "#caa766", serif: true, frame: { inset: 14, border: "1px solid #caa766", radius: 2, innerBorder: "1px solid rgba(202,167,102,0.4)", innerInset: 20 } },
  { key: "lux-ivory-accent", label: "Ivory Accent", desc: "Cream accent frame", category: "Luxury & Elegant", bg: "linear-gradient(160deg,#1a1410 0%,#120d0a 60%,#0a0706 100%)", headInk: "#f5e9d0", subInk: "#d8cbb3", eyeInk: "@accent", serif: true, frame: { inset: 15, border: "1px solid @accent", radius: 2, innerBorder: "1px solid rgba(245,233,208,0.35)", innerInset: 21 } },
  { key: "lux-sapphire-noir", label: "Sapphire Noir", desc: "Sapphire jewel tone", category: "Luxury & Elegant", bg: "radial-gradient(120% 120% at 30% 10%,#1b2c52 0%,#101d3a 45%,#080f20 100%)", headInk: "#e8d9a8", subInk: "#bcc7df", eyeInk: "#dcc488", serif: true, glow: true },
  { key: "dark-obsidian-gold", label: "Obsidian Gold", desc: "Black metallic gold", category: "Dark Premium", bg: "linear-gradient(150deg,#141414 0%,#0c0c0c 55%,#040404 100%)", headInk: "#eccb93", subInk: "#b9b2a4", eyeInk: "#d9b876", glow: true, frame: { inset: 16, border: "1px solid rgba(236,203,147,0.55)", radius: 4, innerBorder: "1px solid rgba(236,203,147,0.18)", innerInset: 22 } },
  { key: "dark-graphite-steel", label: "Graphite Steel", desc: "Brushed charcoal metal", category: "Dark Premium", bg: "linear-gradient(135deg,#26282b 0%,#191b1d 50%,#0d0e10 100%)", headInk: "#eef1f4", subInk: "#aab2bb", eyeInk: "@accent" },
  { key: "dark-onyx-accent", label: "Onyx Accent", desc: "Restrained dark glow", category: "Dark Premium", bg: "radial-gradient(130% 110% at 50% 0%,#1a1a1d 0%,#101012 50%,#050506 100%)", headInk: "#f2efe9", subInk: "#9c9a96", eyeInk: "@accent", glow: true, frame: { inset: 18, border: "1px solid rgba(255,255,255,0.12)", radius: 6, innerBorder: "1px solid @accent", innerInset: 24 } },

  // ── Playful & Vibrant / Gradient Mesh ──────────────────────────────────
  { key: "play-sunset-pop", label: "Sunset Pop", desc: "Warm tropical glow", category: "Playful & Vibrant", bg: "linear-gradient(135deg, #ff6b6b 0%, #ffa64d 45%, #ffd166 100%)", headInk: "#ffffff", subInk: "rgba(255,255,255,0.92)", eyeInk: "rgba(255,255,255,0.78)", glow: true },
  { key: "play-cotton-candy", label: "Cotton Candy", desc: "Soft pastel sky", category: "Playful & Vibrant", bg: "linear-gradient(120deg, #fbc2eb 0%, #a6c1ee 100%)", headInk: "#3b0764", subInk: "rgba(59,7,100,0.82)", eyeInk: "rgba(59,7,100,0.65)", frame: { inset: 14, border: "2px solid rgba(255,255,255,0.85)", radius: 8 } },
  { key: "play-tropic-punch", label: "Tropic Punch", desc: "Lush lime mango", category: "Playful & Vibrant", bg: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)", headInk: "#063b2e", subInk: "rgba(6,59,46,0.85)", eyeInk: "rgba(6,59,46,0.68)" },
  { key: "play-berry-blast", label: "Berry Blast", desc: "Bold magenta berry", category: "Playful & Vibrant", bg: "linear-gradient(135deg, #c31432 0%, #ec008c 55%, #fc6767 100%)", headInk: "#ffffff", subInk: "rgba(255,255,255,0.9)", eyeInk: "rgba(255,255,255,0.75)", glow: true },
  { key: "play-bubblegum-brand", label: "Bubblegum", desc: "Candy accent splash", category: "Playful & Vibrant", bg: "linear-gradient(135deg, @accent 0%, #ff9a9e 50%, #fecfef 100%)", headInk: "#ffffff", subInk: "rgba(255,255,255,0.92)", eyeInk: "rgba(255,255,255,0.78)", glow: true },
  { key: "mesh-aurora-dream", label: "Aurora Dream", desc: "Dreamy aurora mesh", category: "Gradient Mesh", bg: "radial-gradient(at 0% 0%, #f0abfc 0, transparent 50%), radial-gradient(at 100% 0%, @accent 0, transparent 50%), radial-gradient(at 100% 100%, #34d399 0, transparent 50%), radial-gradient(at 0% 100%, #60a5fa 0, transparent 50%), #1e1b4b", headInk: "#ffffff", subInk: "rgba(255,255,255,0.88)", eyeInk: "rgba(255,255,255,0.7)", glow: true },
  { key: "mesh-ocean-bloom", label: "Ocean Bloom", desc: "Deep tide mesh", category: "Gradient Mesh", bg: "radial-gradient(at 10% 20%, #22d3ee 0, transparent 45%), radial-gradient(at 90% 10%, @accent 0, transparent 50%), radial-gradient(at 80% 90%, #2563eb 0, transparent 55%), radial-gradient(at 20% 100%, #14b8a6 0, transparent 50%), #0b1f3a", headInk: "#ffffff", subInk: "rgba(255,255,255,0.86)", eyeInk: "rgba(255,255,255,0.68)", frame: { inset: 14, border: "2px solid rgba(255,255,255,0.75)", radius: 8 } },
  { key: "mesh-berry-twilight", label: "Berry Twilight", desc: "Plum sunset mesh", category: "Gradient Mesh", bg: "radial-gradient(at 0% 10%, #fb7185 0, transparent 50%), radial-gradient(at 100% 0%, #a855f7 0, transparent 50%), radial-gradient(at 90% 100%, @accent 0, transparent 55%), radial-gradient(at 0% 100%, #6366f1 0, transparent 50%), #2a0a3f", headInk: "#ffffff", subInk: "rgba(255,255,255,0.88)", eyeInk: "rgba(255,255,255,0.7)", glow: true },
  { key: "mesh-citrus-fizz", label: "Citrus Fizz", desc: "Bright pastel mesh", category: "Gradient Mesh", bg: "radial-gradient(at 0% 0%, #fef08a 0, transparent 50%), radial-gradient(at 100% 0%, #fdba74 0, transparent 50%), radial-gradient(at 100% 100%, @accent 0, transparent 55%), radial-gradient(at 0% 100%, #86efac 0, transparent 50%), #fff7ed", headInk: "#7c2d12", subInk: "rgba(124,45,18,0.82)", eyeInk: "rgba(124,45,18,0.65)" },

  // ── Retro & Vintage / Organic & Natural ────────────────────────────────
  { key: "retro-midcentury-mod", label: "Mid-Century Mod", desc: "Warm atomic era", category: "Retro & Vintage", bg: "linear-gradient(160deg,#f3e7d3,#e8d3b4)", headInk: "#3a2e22", subInk: "#5c4a36", eyeInk: "#c1492b", serif: true, frame: { inset: 16, border: "3px solid #c1492b", radius: 4, innerBorder: "1px solid #3a2e22", innerInset: 6 } },
  { key: "retro-80s-sunset", label: "80s Sunset", desc: "Synthwave dusk stripes", category: "Retro & Vintage", bg: "linear-gradient(180deg,#f4a261 0%,#f4a261 30%,#e76f51 30%,#e76f51 55%,#9d4edd 55%,#5a189a 100%)", headInk: "#fdf3e7", subInk: "#f0d8c4", eyeInk: "#ffd166", glow: true },
  { key: "retro-vintage-paper", label: "Vintage Paper", desc: "Aged cream press", category: "Retro & Vintage", bg: "#efe6d4", headInk: "#2d2a24", subInk: "#5a5040", eyeInk: "#a8531f", serif: true, frame: { inset: 18, border: "2px solid #8a6d4b", radius: 2, innerBorder: "1px solid #8a6d4b", innerInset: 5 } },
  { key: "retro-mustard-teal", label: "Mustard Teal", desc: "Bold 70s contrast", category: "Retro & Vintage", bg: "linear-gradient(135deg,#e9b949,#d99a2b 60%,#1d6f6f)", headInk: "#2a2018", subInk: "#fdf3e7", eyeInk: "#e76f51", serif: true },
  { key: "retro-sunburst-rays", label: "Sunburst Rays", desc: "Radial retro glow", category: "Retro & Vintage", bg: "radial-gradient(circle at 50% 120%,#ffd166 0%,#f4a261 35%,#e76f51 70%,#9d4520 100%)", headInk: "#3a2012", subInk: "#5c2e18", eyeInk: "#fdf3e7", serif: true, glow: true, frame: { inset: 14, border: "3px double #fdf3e7", radius: 8 } },
  { key: "org-sage-calm", label: "Sage Calm", desc: "Soft herbal neutral", category: "Organic & Natural", bg: "linear-gradient(160deg,#dfe3d2,#c4cdb2)", headInk: "#33402b", subInk: "#55603f", eyeInk: "#7d6b4f", frame: { inset: 18, border: "1px solid #9aa67e", radius: 6 } },
  { key: "org-terracotta-clay", label: "Terracotta Clay", desc: "Warm earthen tone", category: "Organic & Natural", bg: "linear-gradient(155deg,#e2a584,#c97b57)", headInk: "#3d2418", subInk: "#5e3a28", eyeInk: "#f4e9dd", serif: true },
  { key: "org-sand-dune", label: "Sand Dune", desc: "Pale desert neutral", category: "Organic & Natural", bg: "#e9e0cf", headInk: "#4a3f2e", subInk: "#6b5d45", eyeInk: "#b07a48", frame: { inset: 16, border: "1px solid #c2b394", radius: 4, innerBorder: "1px solid #c2b394", innerInset: 5 } },
  { key: "org-olive-grove", label: "Olive Grove", desc: "Muted earthy green", category: "Organic & Natural", bg: "linear-gradient(165deg,#d9d2bd,#a9a074)", headInk: "#34301f", subInk: "#54503a", eyeInk: "#8a5a3c", serif: true },
];

export const DESIGN_STYLES: StyleDef[] = [...CLASSIC_STYLES, ...EXTRA_STYLES];

export const STYLE_BY_KEY: Record<string, StyleDef> = Object.fromEntries(DESIGN_STYLES.map((s) => [s.key, s]));

// Ordered list of categories as they first appear — used to group the Style tab.
export const STYLE_CATEGORIES: string[] = DESIGN_STYLES.reduce<string[]>((acc, s) => (acc.includes(s.category) ? acc : [...acc, s.category]), []);

const sub = (v: string, accent: string) => (v.includes("@accent") ? v.split("@accent").join(accent) : v);

/** Resolve a style key (+ brand accent) into concrete render values. */
export function resolveStyle(key: string | undefined, accent: string): ResolvedStyle {
  const s = (key && STYLE_BY_KEY[key]) || STYLE_BY_KEY.modern;
  const frame = s.frame
    ? {
        ...s.frame,
        border: s.frame.border ? sub(s.frame.border, accent) : s.frame.border,
        innerBorder: s.frame.innerBorder ? sub(s.frame.innerBorder, accent) : s.frame.innerBorder,
      }
    : undefined;
  return {
    bg: sub(s.bg, accent),
    bgImage: s.bgImage,
    headInk: sub(s.headInk, accent),
    subInk: sub(s.subInk, accent),
    eyeInk: sub(s.eyeInk, accent),
    serif: !!s.serif,
    glow: !!s.glow,
    frame,
  };
}
